<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>From the house of Roperro</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <?php include "header-includes.php";?>

</head>

<body>

  <?php include "header.php";?>
  
 
  <main id="main">

    <!-- ======= T&C Section ======= -->
    <section>
      <div class="container">
        <div class="row">
           <div class="tc-heading">
              <h3 class="secondary-font">Terms & Conditions</h3>
              <p>Welcome to ROPERRO!</p>
              <p>The portal, <b>Roperro.COM</b> (“<b>Website</b>”) is managed and operated by ROPERRO PRIVATE LIMITED, Registered office: B-47, SECTOR 57, <br> <br>
                NOIDA-201301 (“<b>Roperro</b>”), a public company incorporated under the Companies Act, 1956. Roperro enables sale and purchase of diverse range of products listed on the Platform from time to time (“<b>Services</b>”).</p>               
              <p>1. TERMS AND CONDITIONS FOR USE OF THE PLATFORM</p>
              <p>1.1. Any person who access and/or use the Platform in any manner (referred as ”you”, “your”), shall be subject to these terms and conditions for use and be bound by the policies formulated by Roperro</p>
              <p>1.2. These terms and conditions for use, the policies as list above, and such other policies or terms as may be prescribed by Roperro (“<b>Terms</b>”), together constitute a legally binding agreement between the You and Roperro, in connection with the access to or use of the </p>
              <p>Platform. You are requested to read these Terms carefully before accessing or using the Platform.</p>
              <table>
              <tr class ="table-heading">
                  <td>Name of Policy</td>
                  <td>Objective</td>
                  <td>Link</td>
                </tr>
                <tr>
                  <td>Privacy Policy</td>
                  <td>Explains how any personal information disclosed by Users is collected, used and managed</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Delivery policy</td>
                  <td>Explains how Products are delivered upon order</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Cancellation, Return and Refund Policy</td>
                  <td>Explains the manner in which Products can be cancelled, returned and refunds credited.</td>
                  <td></td>
                </tr>
              </table>
              <p>1.3. Roperro may update/modify/amend these Terms (including any portion of it) at any time, with or without advance notice.</p>
              <p>1.4. Using the Services or accessing the Platform constitute your consent to the Terms. By using the Platform, You signify your acceptance of these Terms and agrees to be legally bound by them. If at any time, you do not agree or wish to be bound by these Terms, you may not access use the Platform. These Terms supersede all previous terms and conditions communicated to you by Roperro, for the use of the Platform and all rights and liabilities of Roperro with respect to any Services to be provided will be limited to the scope of these Terms.</p>
              <p>1.5. This document is an electronic record in terms of the Information Technology Act, 2000 (“<b>IT Act</b>”) and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the IT Act. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
              <p>1.6. In addition to these Terms, you may be required to comply with the terms and conditions of the third parties, whose links are contained/embedded in the Services. It is hereby clarified that Roperro shall not be held liable for any transaction between the User and any such third parties.</p>
              <p>2. REGISTRATION</p>
              <p>1.1 <b> Registration.</b> In order to avail the Services you will be required to register on the Platform. Registration is a one-time process and is free of cost. You may register in one of the following ways:</p>
              <p>1.1.1 <b>By creating an Roperro account:</b> by providing the relevant information for the creation of your account on the Platform. Following this, an account with an exclusive user name and password (basis your inputs) will be created by Roperro for you.</p>
              <p>1.1.2 <b>By using a third-party account:</b> you may use the login credentials of the account maintained by the User with a Roperro-integrated third-party (illustratively, Google or Facebook), in which case you will also be subject to relevant third-party terms and conditions applicable to such account.</p>
              <p>2. USER WARRANTIES AND RESTRICTIONS</p>
              <p>2.1 You may use the Platform for reasonable and lawful purposes only, and shall not indulge in any activity that is unlawful or harmful to the Platform or its content. You are provided with a limited license to access and use the Platform, solely for the purpose of availing the Services, subject to these Terms.</p>
              <p>2.2 You will not:</p>          
              <p>2.2.1 Delete or modify any content on the Platform, including but not limited to, any information regarding the Services, their performance, sales or pricing, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that the you do not own or have express permission to modify;</p>
              <p>2.2.2 Decompile, reverse engineer, or disassemble the content;</p>
              <p>2.2.3 Use the Services in any way that is unlawful, or harms Roperro or any other person or entity, as determined in Roperro’s sole discretion;</p>
              <p>2.2.4 Using any engine, software, tool, agent or other mechanism (such as spiders, robots, avatars, worms, time bombs, Easter eggs, cancel bots, intelligent agents, etc.) to navigate or search the Platforms;</p>
              <p>2.2.5 Make false or malicious statements against the Services, the Platform or Roperro;</p>
              <p>2.2.6 Post, copy, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Platform and/or Services or any connected network, or otherwise interfere with any person or entity's use or enjoyment of the Platform and/or the Services;</p>
              <p>2.2.7 Engage in any form of antisocial, disruptive, or destructive acts, including “flaming,” “spamming,” “flooding,” “trolling,”, “phishing” and “griefing” as those terms are commonly understood and used on the internet; or</p>
              <p>2.2.8 Post or upload any content that is libelous, defamatory, abusive, threatening, harassing, hateful, and offensive or otherwise violates any law or right of any third-party.</p>
              <p>2.3 Do not host, display, upload, modify, publish, transmit, update or share on or through the Platform, any information that:</p>
              <p>2.3.1 belongs to another person and to which they do not have any right;</p>
              <p>2.3.2 is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise harmful in any manner whatsoever;</p>
              <p>2.3.3 Harms minors in any way;</p>
              <p>2.3.4 Infringes any patent, trademark, copyright or other proprietary rights;</p>
              <p>2.3.5 violates any law for the time being in force;</p>
              <p>2.3.6 Deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
              <p>2.3.7 Impersonates or defames another person; or</p>
              <p>2.3.8 Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</p>
              <p>2.4 You are solely responsible for maintaining the confidentiality of your Account Information and for restricting access to your computer or mobile or other similar device to prevent unauthorized access to their account. You are requested to safeguard your password and your account and make sure that others do not have access to it. It is the you responsibility to keep your Account Information current and accurate. You agree to: (a) immediately notify Roperro of any unauthorized use of the account or any other security breach; and (b) ensure that they exit from their account at the end of each session. Roperro will not be liable for any loss or direct or indirect damage arising from the User’s failure to comply with these conditions. You may be held liable for any losses incurred to Roperro or any other user due to unauthorized use of your account, resulting from the failure to keep your Account Information secure and confidential.</p>
              <p>2.5 You will not be involved in the transmission of sensitive and personal information, including but not limited to Account Information (collectively “<b>SPI</b>”), which falls within the ambit of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, while accessing or using the Platform.</p>
              <p>2.6 You represent and warrant to Roperro that: (a) you are 18 (eighteen) years of age or older; (b) your use of the Platform and/or Services will not violate any applicable law or regulation; and (c) all information that is submitted to Roperro in connection with the Platform and/or Services is true and accurate.</p>
              <p>3. CONTENT ON PLATFORM</p>
              <p>3.1 All information, content and material contained on the Platform are and continue to be Roperro’s or relevant third party intellectual property. Further, all trademarks, services marks, trade names and trade secrets in relation to the Platform whether or not displayed on the Platform, are proprietary to Roperro or relevant third party. No information, content or material from the Platform may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way without our express written permission. Any unauthorized use terminates the permissions granted in these Terms.</p>
              <p>3.2 The contents of Services, information, text, graphics, images, logos, button icons, software code, interface, design and the collection, arrangement and assembly of the content on the Platforms or any of the other Services are the property of Roperro or its affiliates or relevant third party (“<b>Content</b>”), and are protected under copyright, trademark and other applicable laws. The User shall not modify the Content or reproduce, display, publicly perform, distribute, reverse engineer or otherwise use the Content in any way for any public or commercial purpose or for personal gain.</p>
              <p>3.3 Roperro authorises you to view and access Content solely for identifying Products, carrying out purchases of Products and processing returns and refunds, in accordance with Return and Refund Policy. Roperro, therefore, grants to you a limited, revocable license to access and use the Services. This license does not include a permission for carrying out any resale of the Products or commercial use of the Content, any collection and use of product listings, description, or prices, and, any derivative use of the Platforms or of Content.</p>
              <p>3.4 You hereby grant to Roperro a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material, review, feedback, comments etc., posted by you on the Platform without additional approval or consideration in any form, media, or technology now known or later developed, for the full term of any rights that may exist in such content, and the you waive any claim to the contrary over all feedback, comments, ideas or suggestions or any other content provided by them to Roperro through the Platform.</p>
              <p>4. MANNER OF USE OF PLATFORM</p>
              <p>4.1 Display of Products for purchase on the Platforms is merely an invitation to offer. An order placed by you for purchase of a Product constitutes an offer. All orders placed by you on the Platforms are subject to the availability of such Product, Roperro’s acceptance of you offer and your continued adherence to these Terms. You acknowledge and undertake that you are accessing the Services provided on the Platform and are transacting at your own risk and are using your best judgment before entering into any transactions through the Platform. You may place the orders on the Platform for the products and at the price indicated therein.</p>
              <p>4.2 You agree and acknowledge that you will have to make the requisite payment for the Services availed by them on the Platform. Roperro accepts online payments using either credit card, debit card, net banking, digital wallets or other payment options as made available by the Platform from time to time. The payments made by you through the Platform for the purchase of the Products, is subject to the Fees and Payment Policy.</p>
              <p>4.3 Upon payment of the consideration for the Products or undertaking to pay for the Product (in case of cash on delivery), the Product shall be delivered to you, in accordance with the Delivery Policy.</p>
              <p>4.4 All information in relation to third parties, including sellers and the Products as available on the Platforms (“<b>Third Party Information</b>”) are provided solely for reference. Roperro is not endorsing the Third Party Information and is not responsible for any errors and representation nor is it associated with it and you access the Third Party Information at the your own risk</p>
              <p>4.5 If you may cancel any order made on the Platform, return the Products purchased on the Platform as per Cancellation, Returns and Refund Policy.</p>
              <p>5. DISCLAIMER OF WARRANTIES</p>
              <p>5.1 Roperro will try to make access to and use of the Platform error-free. However, your access to the Platform may be suspended or restricted to allow for repairs, maintenance, or for introduction of new facilities or services. Please note that Roperro does not take responsibility for any access or use problems that arise from internet related issues at your end. Roperro reserves at all times, the right, at its sole discretion, to refuse access to the Platform, terminate accounts, remove or edit content at its discretion.</p>
              <p>5.2 The Platform may contain user generated content which Roperro does not pre-screen and which contains views that may be opinions of users and also of experts. Roperro does not claim any ownership rights to the text, files, images including photos, videos, sounds, musical works or any user generated content that you may submit or publish on the Platform. After posting any UGC on the Platform, you continue to own the rights that they may have in that UGC, subject to the limited license set out herein below. Roperro will do its best to monitor, edit or remove such user generated content where it considers it appropriate or necessary to do so. Roperro does not promise that any user generated content on the Platform is accurate, complete or updated, that it will not offend or upset any person or that it does not infringe the intellectual property rights of third parties.</p>
              <p>5.3 As a means to assist you in identifying the Products of your choice, Roperro provides visual representations on the Platforms including graphics, illustrations, photographs, images, videos, charts, screenshots, infographics and other visual aids. While reasonable efforts are made to provide accurate visual representations, Roperro disclaims any guarantee or warranty of exactness of such visual representation or description of the Product, with the actual Product ultimately delivered to you. The appearance of the Product when delivered may vary for various reasons.</p>
              <p>5.4 The Services included on or otherwise made available to you through the Platforms are provided on an “as is” and “as available” basis without any representations or warranties, express or implied, except if otherwise specified in writing. Roperro does not covenant or warrant that:</p>
              <p>5.4.1 The Services will be made available at all times;</p>
              <p>5.4.2 the operation of the Platform, including the functions contained in any content, information and materials on the Platform or any third-party sites or services linked to the Platform will be uninterrupted, timely or error-free, that the defects will be rectified, or that the Platform or the servers that make such content, information and materials available are free of viruses or other harmful components</p>
              <p>5.4.3 The Content available on the Platforms is complete, true, accurate or non-misleading; and</p>
              <p>5.4.4 The Products are of specified merchantability, merchantable quality and fit for use for a particular purpose.</p>
              <p>6. INDEMNIFICATION AND LIMITATION OF LIABILITY</p>
              <p>6.1 You agree to indemnify, defend and hold harmless Roperro, its affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney fees and costs) arising from the your access to or use of the Platform or the Services, violation of these Terms, or infringement of any intellectual property or other rights of Roperro or any third-party. Roperro will notify you promptly of any such claim, loss, liability, or demand, and in addition to the foregoing, you agree to provide Roperro with reasonable assistance, at their expense, in defending any such claim, loss, liability, damage, or cost.</p>
              <p>6.2 To the fullest extent permitted by law, in no event shall Roperro or any of its directors, officers, employees, agents or content or service providers (collectively, the “<b>Roperro Representatives</b>”) be liable to you for any direct, indirect, special, incidental, consequential, exemplary, special, remote or punitive damage, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses arising from, or directly or indirectly related to, the use of, or the inability to use, the Platform or the content, materials and functions related thereto, the Services, provision of information via the Platform, lost business, even if such Roperro Representatives have been advised of the possibility of such damages.</p>
              <p>6.3 In no event shall Roperro Representatives be liable for:</p>
              <p>6.3.1 The use or inability to use the Platform and/or the Services;</p>
              <p>6.3.2 Any content posted, transmitted, exchanged or received by or on behalf of any user or other person on or through the Platform;</p>
              <p>6.3.3 Any unauthorized access to or alteration or transmissions of SPI or other user data; or</p>
              <p>6.3.4 Any other matter relating to the Platform or the Services.</p>
              <p>6.4 Roperro is neither liable nor responsible for any actions or inactions of the other users of the Platform or any breach of conditions, representations or warranties by them. Roperro is not obligated to mediate or resolve any dispute or disagreement amongst two or more users of the Platform.</p>
              <p>6.5 None of the directors, officials or employees of Roperro shall be personally liable for any action in connection with the Platform or the Services.</p>
              <p>7. ACCESS OUTSIDE THE REPUBLIC OF INDIA</p>
              <p>7.1 Roperro makes no representation that the content on the Platform is appropriate to be used or accessed outside the Republic of India. Your use or access the Platform from outside the Republic of India, do so at their own risk and are responsible for compliance with the laws of such jurisdiction. These Terms do not constitute, nor may these Terms be used for or in connection with any promotional activities or solicitation by anyone in any jurisdiction in which such promotional activities or solicitation are not authorized or to any person to whom it is unlawful to promote or solicit.</p>
              <p>8. COMMUNICATION AND UNSUBSCRIPTION</p>
              <p>You hereby understands that with your registration onto the Platform, you may receive notifications from Roperro in the form of SMS messages on their registered mobile number or e-mails. These notifications could relate to their registration, transactions that they carry out through the Platform and/or promotions. Further, Roperro may also send notifications and reminders to them with respect to their activity on the Platform, in relation to the Services. Please note that while Roperro endeavors to provide these notifications and reminders to you, Roperro does not provide any guarantee and shall not be held liable or responsible for any failure to send such notifications or reminders to you. The User can unsubscribe / opt-out from receiving communications, newsletters and other notifications from Roperro at any time by following the procedure set forth on the Platform.</p>
              <p>9. TERM AND TERMINATION</p>
              <p>9.1 These Terms shall be effective from the date of their publication on the Platform.</p>
              <p>9.2 Roperro reserves the right to suspend or terminate its Services in the event of breach of any terms contained in these Terms, misrepresentation of information, any unlawful activity by you or if Roperro is unable to verify or authenticate any information submitted by you.</p>
              <p>9.3 You may terminate the Agreement at any time by discontinuing the use of the Platforms or Services. By terminating the usage or the Agreement you will be obligated to pay for a Product purchased on the Platforms, or any other obligation which has accrued, or is unfulfilled and relates to the period, prior to termination.</p>
              <p>10. FORCE MAJEURE</p>
              <p>10.1 Roperro will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond Roperro’s reasonable control.</p>
              <p>11. WAIVER</p>
              <p>11.1 No provision in these Terms will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by Roperro. Any consent by Roperro to, or waiver of a breach by the User, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</p>
              <p>12. SEVERABILITY</p>
              <p>12.1 If any provision of these Terms is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms and the remainder of these Terms will be interpreted as if such provision were so excluded and will be enforceable in accordance with its terms; provided however that, in such event, these Terms will be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.</p>
              <p>13. GRIEVANCE REDRESSAL</p>
              <p>13.1 The User may submit any grievance with respect to the Platform or the Services, including with respect to any abuse on the Platform, including any discrepancies or grievances with respect to processing of information, to the Grievance Officer at:</p>
              <p><b>Name : ROPERRO PRIVATE LIMITED</b></p>
              <p><b>Address : Registered office: B-47, SECTOR 57, NOIDA-201301</b></p>
              <p><b>E-mail ID : grievance.officer@Roperro.com</b></p>
              <p>14. GOVERNING LAW AND DISPUTE RESOLUTION</p>
              <p>14.1 These Terms, all transactions consummated between you and Roperro and the relationship between you and Roperro is governed by the laws of India, without reference to any conflict of laws principles and with an exclusive jurisdiction to the courts of Uttar Pradesh.</p>
              <p>Co name - ROPERRO PRIVATE LIMITED</p>
              <p>CIN no - 09AALCR5670H1ZW</p>
              <p>Registered Address - Registered office: B-47, SECTOR 57, NOIDA-201301</p>
           </div>
        </div>
      </div>
    </section>

    
    
    


  </main><!-- End #main -->

  <?php include "footer.php";?>

  <?php include "footer-includes.php";?>

</body>

</html>